version: 2
updates:
  - package-ecosystem: "yarn"
    directory: "/api"
    schedule:
      interval: "weekly"
  - package-ecosystem: "yarn"
    directory: "/app"
    schedule:
      interval: "weekly"
