name: Automerge CI

on:
  push:
    paths-ignore:
      - 'docs/**'
      - '*.md'
  pull_request:
    paths-ignore:
      - 'docs/**'
      - '*.md'

jobs:
  test:
    uses: dancastillo/workflows/.github/workflows/automerge-ci.yml@main
