name: Playwright Tests
on:
  push:
    branches: [main, master, develop]
  pull_request:
    branches: [main, master, develop]

defaults:
  run:
    working-directory: ./app

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Start app
        run: yarn start
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Run Playwright tests
        run: npx playwright test
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: app/playwright-report/
          retention-days: 30
